version: '2'
services:
  app:
    image: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./www:/var/www
      - ./logs:/var/log
      - ./common:/etc/nginx/common
    ports:
      - 80:80
      - 443:443
